version: "2"

services:

  redis:
    container_name: redis-nojul
    image: redis
    command: redis-server
    expose:
      - 6379

  db:
    container_name: db-nojul
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reopt
      - POSTGRES_PASSWORD=reopt
      - POSTGRES_DB=reopt
    expose:
      - 5432

  celery:
    container_name: celery-nojul
    build:
      context: .
      dockerfile: Dockerfile
    image: base-api-image
    command:  >
      "celery -A reopt_api worker -l info"
    environment:
      - APP_ENV=local
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_HOST=redis
      - JULIA_HOST=host.docker.internal 
    volumes:
      - .:/opt/reopt
    depends_on:
      - db
      - redis

  django:
    container_name: django-nojul
    build:
      context: .
      dockerfile: Dockerfile
    image: base-api-image
    command:  >
      "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    environment:
      - APP_ENV=local
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_HOST=redis
      - JULIA_HOST=host.docker.internal 
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    volumes:
      - .:/opt/reopt

volumes:
  pgdata:
