apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-julia-deployment
  labels:
    app: {{ .Chart.Name }}-julia
spec:
  replicas: {{ .Values.juliaReplicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-julia
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-julia
        appImageTagChecksum: {{ index .Values.werf.image "julia-api" | sha1sum }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - {{ .Chart.Name }}-julia
              - key: appImageTagChecksum
                operator: In
                values:
                  - {{ index .Values.werf.image "julia-api" | sha1sum }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-ecr-image-pull-secret
      containers:
        - name: {{ .Chart.Name }}-julia
          image: {{ index .Values.werf.image "julia-api" }}
          args: ["julia", "--project=/opt/julia_src", "http.jl"]
          ports:
            - containerPort: 8081
          env:
            - name: JULIA_NUM_THREADS
              value: "4"
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-base-config-map
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 5
            timeoutSeconds: 60
            failureThreshold: 10
          resources:
            requests:
              cpu: {{ .Values.juliaCpuRequest | quote }}
              memory: "2000Mi"
            limits:
              cpu: {{ .Values.juliaCpuLimit | quote }}
              memory: "2000Mi"
