apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-julia-deployment
  labels:
    app: {{ .Chart.Name }}-julia
spec:
  replicas: {{ .Values.juliaReplicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-julia
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-julia
    spec:
      containers:
        - name: {{ .Chart.Name }}-julia
{{ tuple "julia-api" . | werf_container_image | indent 10 }}
          args: ["julia", "--project=/opt/julia_src", "http.jl"]
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-base-config-map
          env:
{{ tuple "julia-api" . | werf_container_env | indent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 5
            timeoutSeconds: 60
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 5
