[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
