ingressHost: localhost
appEnv: development
djangoSettingsModule: reopt_api.dev_settings
redisDataVolumeStorageClassName:
redisHost: "{{ .Chart.Name }}-redis-service"
redisPort: 6379
djangoReplicas: 2
celeryReplicas: 2
