ecrAwsRegion: us-east-2
ecrAwsAccessKeyId:
ecrAwsSecretAccessKey:
ingressHost: localhost
appEnv: development
djangoSettingsModule: reopt_api.dev_settings
redisDataVolumeStorageClassName:
juliaHost: "{{ .Chart.Name }}-julia-service"
redisHost: "{{ .Chart.Name }}-redis-service"
redisPort: 6379
djangoReplicas: 2
djangoCpuRequest: "100m"
djangoCpuLimit: "4000m"
djangoMemoryRequest: "800Mi"
djangoMemoryLimit: "800Mi"
celeryReplicas: 6
celeryCpuRequest: "100m"
celeryCpuLimit: "4000m"
celeryMemoryRequest: "700Mi"
celeryMemoryLimit: "700Mi"
juliaReplicas: 6
juliaCpuRequest: "300m"
juliaCpuLimit: "4000m"
juliaMemoryRequest: "3000Mi"
juliaMemoryLimit: "3000Mi"
