appEnv: production
djangoSettingsModule: reopt_api.production_settings
djangoReplicas: 10
djangoMemoryRequest: "2800Mi"
djangoMemoryLimit: "2800Mi"
celeryReplicas: 20
celeryMemoryRequest: "900Mi"
celeryMemoryLimit: "900Mi"
juliaReplicas: 20
juliaCpuRequest: "300m"
juliaMemoryRequest: "8000Mi"
juliaMemoryLimit: "8000Mi"
